### ISSUE TITLE
Prometheus remote-write URL is only getting pushed to the leader unit

### ISSUE THREAD

**Issue by ahmadfsbd** [canonical/grafana-cloud-integrator#12]
### Bug Description

While trying to configure remote-write url on grafana-agent units using the grafana-cloud-integrator charm, the prometheus-url is only getting pushed into the leader unit of the grafana-agent charm. The correct behavior should be that after adding the juju relation between grafana-agent and the cloud-integrator, the loki/prometheus URLs and other configs (credentials) should be pushed to all the grafana-agent units.

### To Reproduce

1. juju deploy grafana-agent # and relate to the existing app with more than one unit.
2. juju deploy grafana-cloud-integrator --channel latest/edge # to jammy machine
3. juju config grafana-cloud-integrator prometheus-url=http://some.domain.name:9090/api/v1/write
4. juju relate grafana-agent:grafana-cloud-config   grafana-cloud-integrator:grafana-cloud-config
5. After a few seconds, observe that the grafana-agent/leader unit has the prometheus-url in /etc/grafana-agent.yaml

  prometheus_remote_write:
  - tls_config:
      insecure_skip_verify: true
    url: http://10.128.172.1/cos-prometheus-0/api/v1/write
  - basic_auth:
      password: ''
      username: ''
    tls_config::
      insecure_skip_verify: true
    url: http://some.domain.name:9090/api/v1/write

6. Note that on all the other (non-leader) units if grafana agent, this is not reflected:

  prometheus_remote_write:
  - tls_config:
      insecure_skip_verify: true
    url: http://10.128.172.1/cos-prometheus-0/api/v1/write

### Environment

juju controller version 3.4/stable in maas VMs (jammy), running on standard PCB setting.

charm channel = latest/edge

### Relevant log output

```shell
~$ juju debug-log --replay --include grafana-cloud-integrator
unit-grafana-cloud-integrator-2: 14:39:37 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 14:44:25 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 14:49:20 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 14:53:34 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 14:58:07 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 15:02:37 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-grafana-cloud-integrator-2: 15:07:09 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
```

**Comment by ca-scribner** [comment]
I can confirm this using @ahmadfsbd's reproduction, doing:

```bash
juju add-model ga1
juju deploy ubuntu -n 2
juju deploy grafana-agent --channel=latest/edge
juju deploy grafana-cloud-integrator --channel latest/edge --config prometheus-url=http://some.domain.name:9090/api/v1/write
juju relate grafana-agent ubuntu
juju relate grafana-agent:grafana-cloud-config grafana-cloud-integrator:grafana-cloud-config

# Then compare the following:
juju ssh grafana-agent/0 -- cat /etc/grafana-agent.yaml | yq .integrations.prometheus_remote_write
juju ssh grafana-agent/1 -- cat /etc/grafana-agent.yaml | yq .integrations.prometheus_remote_write
```

where we see the leader has:
```yaml
- basic_auth:
    password: ''
    username: ''
  tls_config:
    insecure_skip_verify: false
  url: http://some.domain.name:9090/api/v1/write
```

whereas the other unit has an empty list.

This appears to be due to the leader guards [here](https://github.com/canonical/grafana-cloud-integrator/blob/545e53b13d2408ce0dbd7f56e3f971735c78a384/lib/charms/grafana_cloud_integrator/v0/cloud_config_requirer.py#L55-L63), where the library does nothing on relation changed/broken if the unit is not a leader.  

Non-leader units have somewhat restricted access to relation application_data, where they cannot read/write to their side of the data **but they can read the remote's application_data**.  Since the requirer class here only reads data from the remote application_data, the guard appears unnecessary so the fix should be to remove it.

**Comment by ca-scribner** [comment]
fixed the root cause, but still need to implement the fix in grafana-agent charms

**Comment by ca-scribner** [comment]
The grafana-agent machine charm now uses this lib in its amd releases in:
* 20.04: rev249
* 22.04: rev250

arm releases are blocked by an unrelated bug
